/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Lu7G8eB48qQ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter,
} from '@/components/ui/card';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

export function ExerciseCard() {
  return (
    <Card className="w-full max-w-md">
      <CardContent className="flex flex-wrap gap-2">
        <div>Upper Body</div>
        <div>Strength</div>
        <div>Beginner</div>
        <div>Core</div>
        <div>Cardio</div>
      </CardContent>
      <CardHeader>
        <CardTitle>Pushups</CardTitle>
        <CardDescription>
          Strengthen your chest, shoulders, and triceps with this classic exercise.
        </CardDescription>
      </CardHeader>
      <CardFooter className="flex items-center justify-between">
        <Link href="#" target="_blank" className="text-primary hover:underline" prefetch={false}>
          Learn
        </Link>
        <div className="flex gap-4">
          <Button variant="secondary" className="px-4 py-2">
            Skip
          </Button>
          <Button className="px-6 py-2">Done</Button>
        </div>
      </CardFooter>
    </Card>
  );
}
